name: ci

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
       - 'v*'

jobs:
  build:
    name: 'build / sign'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
        
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r -D rickrollnt-chrome.zip src/
        
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r -D rickrollnt-firefox.zip src/
        
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r -D rickrollnt-opera.zip src/
        
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r -D rickrollnt-edge.zip src/

    - name: cx artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rickrollnt-chrome.zip
        path: ${{ github.workspace }}/rickrollnt-chrome.zip

    - name: ff artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rickrollnt-firefox.zip
        path: ${{ github.workspace }}/rickrollnt-firefox.zip

    - name: op artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rickrollnt-opera.zip
        path: ${{ github.workspace }}/rickrollnt-opera.zip
        
    - name: edge artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rickrollnt-edge.zip
        path: ${{ github.workspace }}/rickrollnt-edge.zip
